const ITEMS=[
{type:'mcq',area:'Science',icon:'🌱',topic:'Life cycles',indicator:'Ref. I.CN.2.1.1 · Recognizes and sequences the life cycle of plants and animals.',prompt:'Rex plants a seed. What happens next?',choices:['A small root begins to grow','The seed becomes a rock','A butterfly comes out','The seed starts to sing'],correct:0,hint:'Think about the first change during germination.',value:.5},
{type:'mcq',area:'Science',icon:'🦴',topic:'Animal characteristics',indicator:'Ref. I.CN.2.2.1 · Identifies animals by their observable characteristics and presence or absence of a backbone.',prompt:'Which animal is a vertebrate?',choices:['Dog','Butterfly','Worm','Snail'],correct:0,hint:'A vertebrate has a backbone.',value:.5},
{type:'mcq',area:'Science',icon:'🌳',topic:'Habitats',indicator:'Ref. I.CN.2.3.1 · Identifies local habitats and proposes actions for their protection.',prompt:'Which action protects an animal habitat?',choices:['Put trash in the correct bin','Cut down every tree','Throw plastic into a river','Scare the animals'],correct:0,hint:'Choose the action that keeps nature clean.',value:.5},
{type:'mcq',area:'Science',icon:'🧼',topic:'Body and health',indicator:'Ref. I.CN.2.4.2 · Recognizes habits that protect the body and support a healthy life.',prompt:'What should Rex do before eating?',choices:['Wash his hands with soap','Play in the mud','Touch the floor','Skip every meal'],correct:0,hint:'This habit removes germs.',value:.5},
{type:'mcq',area:'Science',icon:'💧',topic:'States of matter',indicator:'Ref. I.CN.2.5.1 · Differentiates solids, liquids and gases using observable characteristics.',prompt:'Which one is a liquid?',choices:['Water','Ice cube','Wooden block','Pencil'],correct:0,hint:'A liquid flows and takes the shape of its container.',value:.5},
{type:'mcq',area:'Social Studies',icon:'👨‍👩‍👧',topic:'Family',indicator:'Ref. I.CS.2.1.1 · Recognizes family diversity, rights and responsibilities.',prompt:'Which action is a responsibility at home?',choices:['Put away your toys','Break family rules','Take things without asking','Leave every mess'],correct:0,hint:'A responsibility helps the family.',value:.5},
{type:'mcq',area:'Social Studies',icon:'🏫',topic:'School community',indicator:'I.CS.2.3.1 · Recognizes the school as a place for learning, socialization and identity.',prompt:'Why is school important?',choices:['We learn and live together','We go there only to sleep','It is only for adults','It has no rules'],correct:0,hint:'Think about classmates and teachers.',value:.5},
{type:'mcq',area:'Social Studies',icon:'🏘️',topic:'Community',indicator:'Ref. I.CS.2.4.1 · Recognizes relevant characteristics, people and services of the local community.',prompt:'Who helps put out fires in the community?',choices:['Firefighter','Baker','Musician','Painter'],correct:0,hint:'This person uses a fire truck.',value:.5},
{type:'mcq',area:'Social Studies',icon:'🗺️',topic:'Location',indicator:'DCD CS.2.2.1 · Locates home, school and community using reference points and simple graphic representations.',prompt:'What helps us find places and follow a route?',choices:['A map','A song','A spoon','A pillow'],correct:0,hint:'It can show roads, places and symbols.',value:.5},
{type:'mcq',area:'Social Studies',icon:'🇪🇨',topic:'Ecuador',indicator:'Ref. I.CS.2.6.1 · Recognizes Ecuador as part of South America and values its diversity.',prompt:'Ecuador is part of which continent?',choices:['South America','Europe','Asia','Africa'],correct:0,hint:'Ecuador is in the Americas.',value:.5},
{type:'listening',area:'Listening',icon:'🎧',topic:'English skill',indicator:'Follows a short, clear oral message and identifies explicit information.',prompt:'Listen to Rex. Where does he live?',audio:'Rex is a friendly dinosaur. He lives in a green forest near a river. Where does Rex live?',choices:['In a green forest','In a school bus','On the Moon','In a supermarket'],correct:0,hint:'Press Listen again and focus on the place.',value:1.25},
{type:'reading',area:'Reading',icon:'📖',topic:'Short reading',indicator:'Reads a short familiar text and identifies explicit information.',passage:'Rex is a small green dinosaur. Every morning, he drinks water and eats leaves. Then he helps his friends clean the forest.',prompt:'What does Rex eat?',choices:['Leaves','Rocks','Shoes','Books'],correct:0,hint:'Read the second sentence again.',value:1.25},
{type:'speaking',area:'Speaking',icon:'🗣️',topic:'Oral response',indicator:'Communicates a simple idea using familiar words and an understandable short sentence.',prompt:'Tell Teacher Majo: What animal do you like and why?',task:'Use this model if you need help: “I like ___ because it is ___.”',value:1.25},
{type:'writing',area:'Writing',icon:'✍️',topic:'Written response',indicator:'Writes one relevant simple sentence using familiar vocabulary.',prompt:'Write one sentence about Rex.',task:'You can write about his color, food, home or an action.',value:1.25}
];
const $=id=>document.getElementById(id);
let index=0,score=0,eggs=0,student='',log=[],usedHelp={fifty:false,rex:false},writing='',speakingDone=false,currentChoices=[],rubricIndex=null;
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function start(){student=$('studentName').value.trim();if(!student){$('nameError').textContent='Please write the student’s name.';return}$('nameError').textContent='';index=score=eggs=0;log=[];writing='';speakingDone=false;usedHelp={fifty:false,rex:false};$('studentLabel').textContent=student;show('gameScreen');render()}
function render(){const item=ITEMS[index];$('questionNumber').textContent=index+1;$('progressBar').style.width=`${((index+1)/ITEMS.length)*100}%`;$('subjectPill').textContent=item.area;$('topicLabel').textContent=`${item.icon} ${item.topic}`;$('streakLabel').textContent=`🥚 Eggs: ${eggs}`;$('questionIcon').textContent=item.icon;$('questionText').textContent=item.prompt;$('clue').className='clue';$('clue').textContent='';$('feedback').className='feedback';$('feedback').textContent='';$('nextBtn').classList.remove('show');$('answers').innerHTML='';$('responseArea').innerHTML='';$('passageCard').className='passage-card';$('passageCard').textContent='';$('fiftyBtn').disabled=usedHelp.fifty||!item.choices;$('rexHelpBtn').disabled=usedHelp.rex||!item.choices;$('speakBtn').style.display=item.type==='writing'||item.type==='speaking'?'none':'inline-block';if(item.passage){$('passageCard').textContent=item.passage;$('passageCard').classList.add('show')}if(item.choices)renderChoices(item);else renderPerformanceTask(item)}
function renderChoices(item){const correctText=item.choices[item.correct];currentChoices=shuffle(item.choices).map(text=>({text,correct:text===correctText}));currentChoices.forEach((c,i)=>{const b=document.createElement('button');b.className='answer';b.dataset.correct=c.correct;b.innerHTML=`<span>${'ABCD'[i]}</span>${c.text}`;b.onclick=()=>answer(b,c,item);$('answers').appendChild(b)});if(item.type==='listening')setTimeout(speakCurrent,350)}
function answer(button,choice,item){document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;if(b.dataset.correct==='true')b.classList.add('correct')});if(choice.correct){score+=item.value;eggs++;button.classList.add('bounce');$('feedback').textContent='🥚 ROAR-SOME! Correct!';$('feedback').className='feedback good';eggPop()}else{button.classList.add('wrong');$('feedback').textContent=`Good try! Rex says: ${item.hint}`;$('feedback').className='feedback bad'}log.push({area:item.area,topic:item.topic,indicator:item.indicator,correct:choice.correct,earned:choice.correct?item.value:0,max:item.value,response:choice.text});$('streakLabel').textContent=`🥚 Eggs: ${eggs}`;showNext()}
function renderPerformanceTask(item){const box=document.createElement('div');box.className='task-card';box.innerHTML=`<strong>${item.icon} Your mission</strong><p>${item.task}</p>`;$('responseArea').appendChild(box);if(item.type==='writing'){const ta=document.createElement('textarea');ta.placeholder='Write your sentence here…';ta.value=writing;ta.oninput=()=>{writing=ta.value;$('nextBtn').classList.toggle('show',writing.trim().length>0)};$('responseArea').appendChild(ta);if(writing.trim())showNext()}else{const wrap=document.createElement('div');wrap.className='task-done';const b=document.createElement('button');b.textContent='✓ I finished speaking';b.onclick=()=>{speakingDone=true;b.textContent='✓ Speaking completed';b.disabled=true;showNext()};wrap.appendChild(b);$('responseArea').appendChild(wrap);if(speakingDone)showNext()}}
function showNext(){$('nextBtn').textContent=index===ITEMS.length-1?'FINISH ADVENTURE ▶':'NEXT MISSION ▶';$('nextBtn').classList.add('show')}
function next(){const item=ITEMS[index];if(!item.choices){log.push({area:item.area,topic:item.topic,indicator:item.indicator,correct:null,earned:null,max:item.value,response:item.type==='writing'?writing:'Oral response completed'})}index++;if(index<ITEMS.length)render();else finish()}
function finish(){const result={id:Date.now(),student,date:new Date().toLocaleString(),autoScore:+score.toFixed(2),science:areaScore('Science'),social:areaScore('Social Studies'),listening:areaScore('Listening'),reading:areaScore('Reading'),speaking:null,writing:null,writingText:writing,log};const data=getResults();data.push(result);saveResults(data);$('scoreValue').textContent=`${result.autoScore.toFixed(2)}/7.50`;$('scoreValue').nextElementSibling.textContent='AUTO SCORE';$('resultMessage').textContent='Teacher Majo will add the Speaking and Writing rubric to calculate the final grade over 10.';$('breakdown').innerHTML=`<span>🔬 Science: <b>${result.science.toFixed(2)}/2.50</b></span><span>🌎 Social: <b>${result.social.toFixed(2)}/2.50</b></span><span>🇬🇧 L + R: <b>${(result.listening+result.reading).toFixed(2)}/2.50</b></span>`;show('resultScreen')}
function areaScore(area){return +log.filter(x=>x.area===area).reduce((n,x)=>n+(x.earned||0),0).toFixed(2)}
function speakCurrent(){const item=ITEMS[index];if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const text=item.type==='listening'?item.audio:item.prompt+' '+(item.choices?item.choices.join('. '):'');const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.72;window.speechSynthesis.speak(u)}
function fifty(){const wrong=shuffle([...document.querySelectorAll('.answer')].filter(b=>b.dataset.correct==='false')).slice(0,2);wrong.forEach(b=>b.classList.add('hidden'));usedHelp.fifty=true;$('fiftyBtn').disabled=true}
function rexHelp(){const item=ITEMS[index];usedHelp.rex=true;$('rexHelpBtn').disabled=true;$('clue').textContent=`🦖 Rex whispers: ${item.hint}`;$('clue').classList.add('show')}
function eggPop(){const e=document.createElement('div');e.className='egg-pop';e.textContent='🥚';document.body.appendChild(e);setTimeout(()=>e.remove(),850)}
function newStudent(){$('studentName').value='';show('startScreen');$('studentName').focus()}
function getResults(){return JSON.parse(localStorage.getItem('rexDiagnosticV2')||'[]')}
function saveResults(data){localStorage.setItem('rexDiagnosticV2',JSON.stringify(data))}
function total(r){return +(r.autoScore+(r.speaking??0)+(r.writing??0)).toFixed(2)}
function renderResults(){const data=getResults();$('resultsBody').innerHTML=data.length?data.map((r,i)=>`<tr><td>${escapeHtml(r.student)}</td><td>${r.science.toFixed(2)}</td><td>${r.social.toFixed(2)}</td><td>${r.listening.toFixed(2)}</td><td>${r.reading.toFixed(2)}</td><td class="${r.speaking==null?'pending':''}">${r.speaking==null?'Pending':r.speaking.toFixed(2)}</td><td class="${r.writing==null?'pending':''}">${r.writing==null?'Pending':r.writing.toFixed(2)}</td><td class="${r.speaking!=null&&r.writing!=null?'final':'pending'}">${r.speaking==null||r.writing==null?'Pending':total(r).toFixed(2)+'/10'}</td><td><button class="rubric-btn" onclick="openRubric(${i})">Open</button></td></tr>`).join(''):'<tr><td colspan="9">No students have completed the assessment yet.</td></tr>'}
function openDashboard(){renderResults();$('teacherDialog').showModal()}
const levels=[{v:0,l:'No evidence',d:'No response or unrelated response.'},{v:.5,l:'Beginning',d:'Responds with substantial support.'},{v:.75,l:'Developing',d:'Communicates part of the idea; some errors affect clarity.'},{v:1,l:'Achieved',d:'Communicates a clear, relevant simple idea.'},{v:1.25,l:'Excellent',d:'Clear, complete and confident response for the level.'}];
function levelInputs(name,current){return `<div class="rubric-levels">${levels.map(x=>`<label><input type="radio" name="${name}" value="${x.v}" ${current===x.v?'checked':''}><b>${x.l} · ${x.v.toFixed(2)}</b><br>${x.d}</label>`).join('')}</div>`}
function openRubric(i){rubricIndex=i;const r=getResults()[i];$('rubricStudent').textContent=r.student;const knowledge=r.log.filter(x=>x.area==='Science'||x.area==='Social Studies').map(x=>`<li>${x.correct?'✅':'❌'} <b>${x.topic}</b> — ${x.indicator}</li>`).join('');$('rubricContent').innerHTML=`<section class="rubric-section"><h3>🔬 Science + 🌎 Social Studies · 5.00 pts</h3><p class="indicator">Five questions per subject; each correct answer is worth 0.50.</p><ul class="indicator">${knowledge}</ul></section><section class="rubric-section"><h3>🎧 Listening · ${r.listening.toFixed(2)}/1.25</h3><p class="indicator">Follows a short oral message and identifies explicit information.</p></section><section class="rubric-section"><h3>📖 Reading · ${r.reading.toFixed(2)}/1.25</h3><p class="indicator">Reads a short familiar text and identifies explicit information.</p></section><section class="rubric-section"><h3>🗣️ Speaking · 1.25 pts</h3><p class="indicator">Relevant idea, familiar vocabulary, understandable pronunciation and a simple sentence.</p>${levelInputs('speakingScore',r.speaking)}</section><section class="rubric-section"><h3>✍️ Writing · 1.25 pts</h3><p class="indicator">Relevant simple sentence, familiar vocabulary, initial capital letter and final punctuation.</p><div class="evidence"><b>Student evidence:</b> ${escapeHtml(r.writingText||'No written response')}</div>${levelInputs('writingScore',r.writing)}</section>`;document.querySelectorAll('#rubricContent input').forEach(x=>x.onchange=updateRubricTotal);updateRubricTotal();$('rubricDialog').showModal()}
function selected(name){const x=document.querySelector(`input[name="${name}"]:checked`);return x?+x.value:null}
function updateRubricTotal(){const r=getResults()[rubricIndex],s=selected('speakingScore'),w=selected('writingScore');$('rubricTotal').textContent=s==null||w==null?`${(r.autoScore+(s||0)+(w||0)).toFixed(2)} / 10 · PENDING`:`${(r.autoScore+s+w).toFixed(2)} / 10`}
function saveRubric(){const s=selected('speakingScore'),w=selected('writingScore');if(s==null||w==null){alert('Please select a level for Speaking and Writing.');return}const data=getResults();data[rubricIndex].speaking=s;data[rubricIndex].writing=w;saveResults(data);$('rubricDialog').close();renderResults()}
function download(){const data=getResults();if(!data.length)return;const head=['Student','Date','Science /2.50','Social Studies /2.50','Listening /1.25','Reading /1.25','Speaking /1.25','Writing /1.25','Final /10','Writing evidence','Indicator results'];const rows=[head,...data.map(r=>[r.student,r.date,r.science.toFixed(2),r.social.toFixed(2),r.listening.toFixed(2),r.reading.toFixed(2),r.speaking==null?'Pending':r.speaking.toFixed(2),r.writing==null?'Pending':r.writing.toFixed(2),r.speaking==null||r.writing==null?'Pending':total(r).toFixed(2),r.writingText,r.log.filter(x=>x.indicator).map(x=>`${x.indicator}: ${x.correct===null?'Manual':x.correct?'Achieved':'Needs support'}`).join(' | ')] )];const csv=rows.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='rex-diagnostic-dashboard.csv';a.click();URL.revokeObjectURL(a.href)}
function clearResults(){if(confirm('Delete all diagnostic results from this device?')){localStorage.removeItem('rexDiagnosticV2');renderResults()}}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
$('startBtn').onclick=start;$('studentName').onkeydown=e=>{if(e.key==='Enter')start()};$('nextBtn').onclick=next;$('newStudentBtn').onclick=newStudent;$('fiftyBtn').onclick=fifty;$('rexHelpBtn').onclick=rexHelp;$('speakBtn').onclick=speakCurrent;$('teacherBtn').onclick=openDashboard;$('closeDialog').onclick=()=>$('teacherDialog').close();$('closeRubric').onclick=()=>$('rubricDialog').close();$('saveRubricBtn').onclick=saveRubric;$('downloadBtn').onclick=download;$('clearBtn').onclick=clearResults;
