const q=(s,u,t,i,text,correct,...wrong)=>({s,u,t,i,q:text,a:[correct,...wrong.slice(0,3)],c:0,h:wrong[3]||'Think carefully and use the picture clue.'});
const Q=[
q('Science',1,'Plant needs','🌱','What does a seed need to begin growing?','Water and warmth','Paint and glue','Only darkness','Plastic and metal','Remember our germination lab.'),
q('Science',1,'Plant life cycle','🌻','Which plant life cycle is correct?','Seed → root → shoot → adult plant','Flower → rock → cloud → seed','Root → egg → fish → plant','Leaf → moon → seed → flower','Start with the seed.'),
q('Science',1,'Germination','🫘','A wet bean seed begins germination. What appears first?','A small root','A flower','A fruit','A wing','It grows down into the soil.'),
q('Science',1,'Living things','🌳','Which fact proves a plant is living?','It grows and needs water','It is green','It stays still','It is in a pot','Living things have needs.'),
q('Science',1,'Animal classification','🦴','An animal with a backbone is a…','Vertebrate','Invertebrate','Plant','Material','Rex has one too.'),
q('Science',1,'Animal classification','🦋','Which animal is an invertebrate?','Butterfly','Dog','Fish','Frog','It has no backbone.'),
q('Science',1,'Vertebrate groups','🐸','Which vertebrate has moist skin and can live on land and in water?','Amphibian','Mammal','Bird','Fish','A frog is an example.'),
q('Science',1,'Vertebrate groups','🦜','Which body covering belongs to birds?','Feathers','Fur','Shell','Wet skin','It helps many birds fly.'),
q('Science',1,'Ecuador habitats','🐢','Where does the giant tortoise naturally live?','Galápagos','A classroom','A snowy city','The deep sea','Its name is the Galápagos giant tortoise.'),
q('Science',1,'Habitat care','🌿','Rex finds trash in an animal habitat. What should he do?','Put it in the correct bin','Throw it in a river','Leave it there','Scare the animals','Protect the animals’ home.'),
q('Science',2,'Vital organs','🧠','Which organ helps you think and control your body?','Brain','Stomach','Heart','Lungs','It is inside your head.'),
q('Science',2,'Vital organs','❤️','Which organ pumps blood around your body?','Heart','Brain','Stomach','Knee','You can feel it beat.'),
q('Science',2,'Vital organs','🫁','Which organs help you breathe?','Lungs','Muscles','Teeth','Joints','They take oxygen from air.'),
q('Science',2,'Vital organs','🍽️','Which organ helps break down food?','Stomach','Heart','Brain','Elbow','Food goes there after you swallow.'),
q('Science',2,'Bones','🦴','What supports your body and protects organs?','Bones','Hair','Nails','Skin color','Your skeleton is made of these.'),
q('Science',2,'Muscles','💪','What pulls on bones to help you move?','Muscles','Lungs','Teeth','Ears','Flex your arm for a clue.'),
q('Science',2,'Joints','🦵','What lets your knee and elbow bend?','Joints','Hair','Lungs','Stomach','Two bones meet here.'),
q('Science',2,'Exercise','🏃','What usually happens after you run?','Breathing and heartbeat get faster','The heart stops','Bones disappear','The stomach becomes a lung','Your body needs more oxygen.'),
q('Science',2,'Hygiene','🧼','Which action removes germs best?','Wash with soap and water','Wipe on clothes','Touch more objects','Rinse for one second','Remember the glitter-germ experiment.'),
q('Science',2,'Healthy habits','😴','Which plan keeps your body healthy?','Good food, exercise, hygiene and rest','Only sweets','No sleep','No water','Your body needs different kinds of care.'),
q('Science',3,'Properties','🥄','Hard and smooth are examples of…','Properties','Habitats','Life cycles','Organs','They describe a material.'),
q('Science',3,'Absorbency','🧽','What is best for cleaning spilled water?','Absorbent cloth','Plastic sheet','Glass marble','Metal coin','Choose what takes in water.'),
q('Science',3,'Natural materials','🪵','Which material comes from nature?','Wood','Plastic','Nylon','Foam','It comes from trees.'),
q('Science',3,'Artificial materials','🧴','Which material is made by people?','Plastic','Wool','Wood','Cotton','Many bottles are made from it.'),
q('Science',3,'Solids','🧊','Which is a solid?','Ice cube','Juice','Air','Steam','It keeps its shape.'),
q('Science',3,'Liquids','💧','Why is water a liquid?','It flows and takes its container’s shape','It keeps one shape','It fills every room','It has roots','You can pour it.'),
q('Science',3,'Gases','🎈','Which example is a gas?','Air in a balloon','A wooden block','An ice cube','A pencil','It fills the balloon.'),
q('Science',3,'Melting','☀️','What happens to ice in the Sun?','It melts','It freezes','It grows','It becomes wood','Heat changes the solid.'),
q('Science',3,'Freezing','❄️','Water becomes ice when it…','Freezes','Melts','Evaporates','Bends','It needs a very cold temperature.'),
q('Science',3,'Temperature','🍫','Why does chocolate soften in warm water?','Heat changes it','Sound changes it','It becomes alive','Cold makes it grow','Warmth can soften solids.'),
q('Science',4,'Energy','⚡','What does energy help things do?','Move, work and change','Become invisible','Stop all sound','Turn into plants','Energy makes things happen.'),
q('Science',4,'Energy sources','🔋','What gives a flashlight energy?','A battery','A leaf','A spoon','A cloud','It goes inside the flashlight.'),
q('Science',4,'Transformation','🚗','A rubber band makes a toy car move. Energy changes into…','Movement','Food','Water','Soil','Watch what the car does.'),
q('Science',4,'Light','🔦','How does light travel from a flashlight?','In a straight line','Around the handle','Only downward','It does not travel','Follow the beam.'),
q('Science',4,'Transparency','🪟','What lets almost all light pass through?','Clear glass','Cardboard','Wood','Metal','You can see clearly through it.'),
q('Science',4,'Shadows','👤','What is needed to make a shadow?','Light and an object','Only sound','Only water','A magnet','The object blocks light.'),
q('Science',4,'Light sources','☀️','Which is a natural light source?','The Sun','A lamp','A flashlight','A screen','People did not make it.'),
q('Science',4,'Sound','🥁','Why does a drum make sound when hit?','It vibrates','It melts','It shines','It freezes','Its surface moves back and forth.'),
q('Science',4,'Volume','🔊','What describes how loud or soft a sound is?','Volume','Texture','Absorbency','Habitat','You change it on a speaker.'),
q('Science',4,'Energy care','💡','How can Rex save energy?','Turn off unused lights','Leave every light on','Open the fridge all day','Use devices nonstop','Use energy only when needed.'),
q('Science',5,'Earth','🌍','Which is the planet where we live?','Earth','Sun','Moon','Mars rock','It has land, water and life.'),
q('Science',5,'Sun','☀️','Which star gives Earth light and heat?','Sun','Moon','Earth','Cloud','We see it during the day.'),
q('Science',5,'Moon light','🌙','Does the Moon make its own light?','No, it reflects sunlight','Yes, it is a lamp','Yes, it is fire','No, it is always dark','Sunlight bounces from it.'),
q('Science',5,'Rotation','🌗','What causes day and night?','Earth rotates','The Moon disappears','Clouds move','Earth stops','Earth turns like a top.'),
q('Science',5,'Day and night','🌞','When your side of Earth faces the Sun, it is…','Day','Night','Winter everywhere','A Moon phase','That side receives light.'),
q('Science',5,'Solar energy','🌡️','Which cup will probably be warmer?','A cup in the Sun','A cup in shade','Both become ice','Neither changes','Sunlight transfers energy.'),
q('Science',5,'Sun and life','🌱','Why is sunlight important for plants?','It gives energy for growth','It gives plastic','It removes all water','It makes soil vanish','Plants use sunlight.'),
q('Science',5,'Moon patterns','🌙','Why does the Moon seem to change shape?','We see different lit parts','It breaks apart','Clouds cut it','It grows pieces','Its visible light follows a pattern.'),
q('Science',5,'Space sizes','🪐','Which is largest?','Sun','Earth','Moon','Classroom globe','The star is much larger.'),
q('Science',5,'Sun safety','🔭','What is the safest Sun-observation rule?','Never look directly at the Sun','Stare with bare eyes','Use toy glasses','Look through any tube','Strong sunlight can hurt eyes.'),
q('Science',6,'Natural resources','🌳','Which is a natural resource?','Water','Plastic toy','Television','Glass cup','It comes from nature.'),
q('Science',6,'Resources','👕','Cotton for a T-shirt comes from…','A plant','A mine','A cloud','A plastic bottle','Cotton grows in fields.'),
q('Science',6,'Renewable resources','☀️','Which resource is naturally replaced quickly?','Sunlight','Oil','Coal','Natural gas','It returns each day.'),
q('Science',6,'Nonrenewable resources','🛢️','Which resource takes millions of years to form?','Oil','Wind','Sunlight','Rainwater','Use this fuel carefully.'),
q('Science',6,'Condensation','☁️','Water vapor cools and forms clouds. This is…','Condensation','Evaporation','Precipitation','Germination','Gas becomes tiny liquid drops.'),
q('Science',6,'Precipitation','🌧️','Rain falling from clouds is…','Precipitation','Evaporation','Condensation','Rotation','Water falls to Earth.'),
q('Science',6,'Evaporation','♨️','The Sun heats water and vapor rises. This is…','Evaporation','Freezing','Precipitation','Germination','Liquid becomes gas.'),
q('Science',6,'Soil','🪱','What helps make soil rich for plants?','Decayed leaves','Plastic wrappers','Glass pieces','Metal cans','Old plant matter adds nutrients.'),
q('Science',6,'Soil care','🌱','What protects soil from erosion?','Planting vegetation','Removing plants','Pouring oil','Leaving it bare','Roots hold soil.'),
q('Science',6,'Conservation','🚰','Which action saves water?','Turn off the tap while brushing','Let water run','Play with the hose','Take a very long shower','Use only what you need.'),
q('Social Studies',1,'Cardinal directions','🧭','Which direction is opposite North?','South','East','West','Left','Look across the compass rose.'),
q('Social Studies',1,'Cardinal directions','🌅','Which direction is opposite East?','West','North','South','Up','The Sun sets there.'),
q('Social Studies',1,'Reference points','🏫','Why is a school a useful reference point?','It helps describe a location','It changes weather','It tells time','It is a direction','People recognize this place.'),
q('Social Studies',1,'Reference points','🏪','“My house is next to the store.” The store is a…','Reference point','Disaster','Province','Symbol','It helps locate the house.'),
q('Social Studies',1,'Plans','🏠','What does a plan show?','A place seen from above','Tomorrow’s weather','A list of animals','A feeling','Imagine looking down.'),
q('Social Studies',1,'Map symbols','🏥','A small hospital picture on a map is a…','Symbol','Province','Border','Disaster','It represents a real place.'),
q('Social Studies',1,'Map key','🗺️','What explains map symbols?','Map key or legend','Clock','Title only','Ruler only','It tells what each picture means.'),
q('Social Studies',1,'Sketches','✏️','What can quickly show a route from home to school?','A sketch','A portrait','A calendar','A song','It is a simple place drawing.'),
q('Social Studies',1,'Maps','🌎','What is a map used for?','Locating and understanding places','Making music','Measuring heat','Growing plants','It guides us.'),
q('Social Studies',1,'Hazards','⚠️','Why show a flood area on a map?','To plan a safe route','To stop rain','To change North','To remove the river','Maps can show danger.'),
q('Social Studies',2,'Urban communities','🏙️','Which describes an urban community?','Many buildings, roads and services','Large farms and few houses','No people','Only animals','Think of a city.'),
q('Social Studies',2,'Rural communities','🚜','Which describes a rural community?','Farms and open land','Many skyscrapers','Only airports','No nature','Think of the countryside.'),
q('Social Studies',2,'Diversity','🤝','What makes a community diverse?','Different cultures and traditions','Everyone is identical','Only buildings differ','Nobody communicates','Differences enrich us.'),
q('Social Studies',2,'Respect','🌈','How should Rex treat another culture?','With respect','By laughing','By excluding it','By changing it','Every culture has value.'),
q('Social Studies',2,'Urban parishes','🏢','An urban parish is usually in…','A city area','The ocean','An empty forest','Another planet','Urban means city.'),
q('Social Studies',2,'Rural parishes','🌾','Which activity is common in rural parishes?','Farming','Subway driving','Building skyscrapers','Operating airports','Open land supports crops.'),
q('Social Studies',2,'Cantons','📍','Which territory contains parishes?','Canton','Classroom','Street','Family','Several parishes form it.'),
q('Social Studies',2,'Provinces','🏞️','Which territory contains cantons?','Province','House','Desk','Crosswalk','Ecuador has 24.'),
q('Social Studies',2,'Local identity','🎭','Which shows local identity?','A community tradition','A broken object','Traffic','An empty page','Traditions connect people and place.'),
q('Social Studies',2,'Community needs','🏥','Why are community services important?','They meet people’s needs','They remove rules','They make all people identical','They replace families','Think health, education and safety.'),
q('Social Studies',3,'Authorities','🏛️','What should a local authority do?','Serve the community','Help only friends','Ignore problems','Damage public places','Authorities work for everyone.'),
q('Social Studies',3,'Canton authority','👩‍💼','Who leads a canton’s municipal government?','Mayor','Class monitor','Shopkeeper','Tourist','This person works at the municipality.'),
q('Social Studies',3,'Authorities','🗣️','A streetlight is broken. What should authorities do?','Organize its repair','Ignore it','Break more lights','Close schools','They respond to community needs.'),
q('Social Studies',3,'Leadership','✅','Which shows responsible leadership?','Listening and finding fair solutions','Helping only one person','Avoiding problems','Keeping everything secret','Good leaders serve all.'),
q('Social Studies',3,'Public services','🚒','Which is a public service?','Fire department','Birthday party','Toy box','Video game','It protects the community.'),
q('Social Studies',3,'Private services','🏪','Which is usually a private service?','Family-owned store','Street lighting','Fire department','Municipal trash collection','A person or company owns it.'),
q('Social Studies',3,'Service care','🚰','How can Rex care for public water service?','Use water responsibly','Leave taps open','Break pipes','Pollute rivers','It belongs to everyone.'),
q('Social Studies',3,'Traffic signs','🛑','What does a red STOP sign mean?','Stop completely','Drive faster','Park anywhere','Turn without looking','Its message is in its name.'),
q('Social Studies',3,'Road safety','🚸','Where should a child cross a street?','At a crosswalk with an adult','Between parked cars','While running anywhere','Behind a bus','Use the marked safe area.'),
q('Social Studies',3,'Rules','🚦','Why follow traffic rules?','To prevent accidents','To make danger','To create confusion','To block every road','Rules protect people.'),
q('Social Studies',4,'Volcanic eruption','🌋','A volcano releases ash and lava. This is a…','Volcanic eruption','Flood','Earthquake','Drought','Think of Cotopaxi.'),
q('Social Studies',4,'Flood','🌊','Water covers normally dry land. This is a…','Flood','Earthquake','Eruption','Drill','Heavy rain can cause it.'),
q('Social Studies',4,'Earthquake','🏚️','Sudden ground shaking is an…','Earthquake','Flood','Cloud','Traffic sign','The ground moves.'),
q('Social Studies',4,'Emergency kit','🎒','What belongs in an emergency kit?','Water, flashlight and first aid','Heavy toys','Glass ornaments','Only candy','Choose useful safety supplies.'),
q('Social Studies',4,'Earthquake safety','🫳','What should you do during an earthquake?','Drop, cover and hold on','Use an elevator','Stand by glass','Push people','Protect your head.'),
q('Social Studies',4,'Evacuation','🚶','After shaking stops, students should…','Follow the teacher to the safe point','Hide alone','Run everywhere','Return for toys','Follow the plan calmly.'),
q('Social Studies',4,'Volcano safety','😷','How do you protect your nose and mouth from ash?','Wear a mask','Breathe deeply outside','Rub your eyes','Open windows','Keep ash out of lungs.'),
q('Social Studies',4,'Flood safety','⛰️','Where should people move in a flood warning?','A safe higher place','Moving water','Under a bridge','The riverbank','Stay away from rising water.'),
q('Social Studies',4,'Safety plan','📋','Why have a family emergency plan?','To know what to do and where to meet','To stop disasters','To change weather','To replace supplies','Planning helps us act safely.'),
q('Social Studies',4,'Shared safety','📢','Who helps with disaster safety?','Authorities and citizens','Only children','Only firefighters','Nobody','Safety is shared work.'),
q('Social Studies',5,'Ecuador','🌎','On which continent is Ecuador?','South America','Europe','Asia','Africa','It is in the Americas.'),
q('Social Studies',5,'Borders','🗺️','Which countries share land borders with Ecuador?','Colombia and Peru','Brazil and Chile','Mexico and Canada','Spain and France','One is north and one is south and east.'),
q('Social Studies',5,'Regions','4️⃣','How many natural regions does Ecuador have?','Four','Two','Seven','Ten','Coast, Highlands, Amazon and Insular.'),
q('Social Studies',5,'Coast','🏖️','Which landscape is common in the Coast Region?','Beaches and lowlands','Polar ice','Only mountains','No rivers','The Pacific touches it.'),
q('Social Studies',5,'Highlands','⛰️','Which feature is important in the Highlands?','Andes Mountains','Coral reefs only','Sandy islands','Amazon River only','Quito is high in this region.'),
q('Social Studies',5,'Amazon','🌳','Which feature is common in the Amazon Region?','Rainforest and rivers','Polar ice','Only cities','Ocean islands','It is warm, wet and biodiverse.'),
q('Social Studies',5,'Insular Region','🐢','What is another name for the Insular Region?','Galápagos','Andes','Amazon','Quito','It is a group of islands.'),
q('Social Studies',5,'Provinces','📍','How many provinces does Ecuador have?','24','4','10','50','They are grouped in regions.'),
q('Social Studies',5,'Megadiversity','🦜','Why is Ecuador megadiverse?','It has many ecosystems, plants and animals','Every place is the same','It has no wildlife','It has one region','Small country, huge biodiversity.'),
q('Social Studies',5,'Identity','🇪🇨','Who are Ecuadorians?','People connected to Ecuador with diverse cultures','People from one city only','People with one tradition','Only authorities','Our identity is diverse.'),
q('Social Studies',6,'Celebrations','🎉','Why are traditional celebrations important?','They preserve culture and memory','They erase identity','They stop cooperation','They replace rights','They connect generations.'),
q('Social Studies',6,'National symbols','🇪🇨','Which is a national symbol?','Ecuadorian flag','Traffic cone','Backpack','Toy dinosaur','It represents our country.'),
q('Social Studies',6,'Flag','🟡','What are Ecuador’s flag colors?','Yellow, blue and red','Green, white and pink','Black and orange','Purple and silver','Yellow is the largest stripe.'),
q('Social Studies',6,'Coat of arms','🛡️','Which symbol includes Chimborazo, a river and a condor?','Ecuador’s coat of arms','Road map','Class plan','Traffic sign','It is on the official flag.'),
q('Social Studies',6,'Solidarity','🤲','A family loses things in a flood. What shows solidarity?','Collect useful supplies','Laugh at them','Ignore them','Take their things','Solidarity means helping.'),
q('Social Studies',6,'Cooperation','🧹','Which shows community cooperation?','Neighbors clean a park together','One person damages it','Everyone litters','Nobody helps','Work toward one goal.'),
q('Social Studies',6,'Reciprocity','🔁','Rex helps Ana; later Ana helps Rex. This is…','Reciprocity','Pollution','A disaster','A border','People give and receive help.'),
q('Social Studies',6,'Relationships','🫶','What builds peaceful relationships?','Respect, dialogue and fair rules','Shouting and pushing','Breaking agreements','Excluding others','Communicate respectfully.'),
q('Social Studies',6,'Rights','📚','Which is a child’s right?','Education','Damaging property','Ignoring rules','Taking things','Children have the right to learn.'),
q('Social Studies',6,'Duties','✅','Which is a citizen’s duty?','Respect laws and public places','Waste resources','Harm people','Ignore the community','Rights come with responsibilities.')
];
const $=id=>document.getElementById(id);let round=[],idx=0,score=0,streak=0,student='',answersLog=[],usedHelp={fifty:false,rex:false};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function balanced(subject){return shuffle([1,2,3,4,5,6].map(unit=>shuffle(Q.filter(x=>x.s===subject&&x.u===unit))[0]))}
function makeRound(){return shuffle([...balanced('Science'),...balanced('Social Studies')])}
function start(){student=$('studentName').value.trim();if(!student){$('nameError').textContent='Please write your name first.';return}$('nameError').textContent='';round=makeRound();idx=score=streak=0;answersLog=[];usedHelp={fifty:false,rex:false};$('studentLabel').textContent=student;show('gameScreen');renderQuestion()}
function renderQuestion(){const item=round[idx];$('questionNumber').textContent=idx+1;$('progressBar').style.width=`${((idx+1)/12)*100}%`;$('subjectPill').textContent=item.s;$('topicLabel').textContent=`${item.i} Unit ${item.u} · ${item.t}`;$('streakLabel').textContent=`🔥 Streak: ${streak}`;$('questionIcon').textContent=item.i;$('questionText').textContent=item.q;$('feedback').textContent='';$('feedback').className='feedback';$('clue').textContent='';$('clue').className='clue';$('nextBtn').classList.remove('show');$('fiftyBtn').disabled=usedHelp.fifty;$('rexHelpBtn').disabled=usedHelp.rex;document.querySelectorAll('.prize-ladder li').forEach(li=>{const n=+li.dataset.step;li.className=n===idx+1?'current':n<=idx?'done':''});const letters=['A','B','C','D'];const choices=shuffle(item.a.map((t,i)=>({t,ok:i===item.c})));$('answers').innerHTML='';choices.forEach((choice,i)=>{const b=document.createElement('button');b.className='answer';b.innerHTML=`<span>${letters[i]}</span>${choice.t}`;b.dataset.correct=choice.ok;b.addEventListener('click',()=>choose(b,choice,item));$('answers').appendChild(b)})}
function choose(button,choice,item){[...document.querySelectorAll('.answer')].forEach(b=>{b.disabled=true;if(b.dataset.correct==='true')b.classList.add('correct')});if(choice.ok){score++;streak++;button.classList.add('bounce');$('feedback').textContent=streak>=3?`🔥 ${streak} IN A ROW! REX-TASTIC!`:'🥚 You found a dino egg! Correct!';$('feedback').className='feedback good';eggPop()}else{streak=0;button.classList.add('wrong');$('feedback').textContent=`Good try! Rex says: ${item.h}`;$('feedback').className='feedback bad'}$('streakLabel').textContent=`🔥 Streak: ${streak}`;answersLog.push({subject:item.s,unit:item.u,topic:item.t,correct:choice.ok,question:item.q});$('nextBtn').textContent=idx===11?'OPEN MY DINO TREASURE ▶':'NEXT MISSION ▶';$('nextBtn').classList.add('show')}
function eggPop(){const e=document.createElement('div');e.className='egg-pop';e.textContent='🥚';document.body.appendChild(e);setTimeout(()=>e.remove(),850)}
function next(){idx++;if(idx<12)renderQuestion();else finish()}
function finish(){const sci=answersLog.filter(x=>x.subject==='Science'),soc=answersLog.filter(x=>x.subject==='Social Studies');const result={student,score,total:12,science:`${sci.filter(x=>x.correct).length}/6`,social:`${soc.filter(x=>x.correct).length}/6`,date:new Date().toLocaleString(),details:answersLog};const data=JSON.parse(localStorage.getItem('rexResults')||'[]');data.push(result);localStorage.setItem('rexResults',JSON.stringify(data));$('scoreValue').textContent=`${score}/12`;$('resultTitle').textContent=score>=11?'Dino Champion!':score>=8?'Rex-tastic work!':score>=6?'Brave Explorer!':'Keep exploring!';$('resultMessage').textContent=score>=11?'Amazing! Your knowledge and English are very strong.':score>=8?'You know many ideas from Science and Social Studies!':score>=6?'Good start! Your answers help Teacher Majo know what to review.':'You were brave and completed every mission. We will learn it together!';$('breakdown').innerHTML=`<span>🔬 Science: <b>${result.science}</b></span><span>🌎 Social Studies: <b>${result.social}</b></span>`;$('resultScreen').classList.toggle('celebrate',score>=8);show('resultScreen')}
function newStudent(){$('studentName').value='';$('resultScreen').classList.remove('celebrate');show('startScreen');$('studentName').focus()}
function fifty(){const wrong=[...document.querySelectorAll('.answer')].filter(b=>b.dataset.correct==='false');shuffle(wrong).slice(0,2).forEach(b=>b.classList.add('hidden'));usedHelp.fifty=true;$('fiftyBtn').disabled=true}
function rexHelp(){usedHelp.rex=true;$('rexHelpBtn').disabled=true;$('clue').textContent=`🦖 Rex whispers: ${round[idx].h}`;$('clue').classList.add('show')}
function speak(){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const item=round[idx];const u=new SpeechSynthesisUtterance(`${item.q}. ${item.a.join('. ')}`);u.lang='en-US';u.rate=.78;window.speechSynthesis.speak(u)}
function safe(x){const d=document.createElement('div');d.textContent=x;return d.innerHTML}
function renderResults(){const data=JSON.parse(localStorage.getItem('rexResults')||'[]');$('resultsBody').innerHTML=data.length?data.map(r=>`<tr><td>${safe(r.student)}</td><td>${r.score}/${r.total||5}</td><td>${r.science}</td><td>${r.social}</td><td>${safe(r.date)}</td></tr>`).join(''):'<tr><td colspan="5">No explorers have played yet.</td></tr>'}
function openResults(){renderResults();$('teacherDialog').showModal()}
function download(){const data=JSON.parse(localStorage.getItem('rexResults')||'[]');if(!data.length)return;const rows=[['Student','Total','Science','Social Studies','Date'],...data.map(r=>[r.student,`${r.score}/${r.total||5}`,r.science,r.social,r.date])];const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='rex-diagnostic-results.csv';a.click();URL.revokeObjectURL(a.href)}
function clearResults(){if(confirm('Delete all saved results from this device?')){localStorage.removeItem('rexResults');renderResults()}}
$('startBtn').onclick=start;$('studentName').addEventListener('keydown',e=>{if(e.key==='Enter')start()});$('nextBtn').onclick=next;$('newStudentBtn').onclick=newStudent;$('fiftyBtn').onclick=fifty;$('rexHelpBtn').onclick=rexHelp;$('speakBtn').onclick=speak;$('teacherBtn').onclick=openResults;$('closeDialog').onclick=()=>$('teacherDialog').close();$('downloadBtn').onclick=download;$('clearBtn').onclick=clearResults;
