const icon=n=>`assets/icons/${n}.svg`;
const I={plant:icon('1f331'),dog:icon('1f415'),butterfly:icon('1f98b'),tree:icon('1f333'),water:icon('1f4a7'),soap:icon('1f9fc'),sun:icon('2600'),cloud:icon('2601'),moon:icon('1f319'),eye:icon('1f441'),ear:icon('1f442'),tooth:icon('1f9b7'),apple:icon('1f34e'),home:icon('1f3e0'),school:icon('1f3eb'),map:icon('1f5fa'),ecuador:icon('1f1ea-1f1e8'),bus:icon('1f68c'),hospital:icon('1f3e5'),family:icon('1f46a'),police:icon('1f46e'),recycle:icon('267b'),walk:icon('1f6b6'),traffic:icon('1f6a6'),fire:icon('1f692'),books:icon('1f4da'),earth:icon('1f30e'),mountain:icon('1f3d4'),desert:icon('1f3d6'),ocean:icon('1f30a')};
const q=(area,topic,indicator,prompt,choices,correct,image,title,detail,hint)=>({area,topic,indicator,prompt,choices,correct,image,title,detail,hint,value:1});
const S='Science',SS='Social Studies';
const science=[
q(S,'Living things','Ref. I.CN.2.1.1','Which one is a living thing?',['A tree','A rock','A chair','A pencil'],0,I.tree,'Living things','They grow and need water.','Living things grow.'),
q(S,'Living things','Ref. I.CN.2.1.1','What does a plant need to grow?',['Water','A toy','A shoe','A book'],0,I.plant,'A small plant','Plants need water and sunlight.','Think about what we give a plant.'),
q(S,'Living things','Ref. I.CN.2.1.1','Which one can grow?',['A puppy','A bus','A table','A spoon'],0,I.dog,'A puppy','Animals grow and change.','An animal is alive.'),
q(S,'Living things','Ref. I.CN.2.1.1','Which one is NOT living?',['A rock','A butterfly','A dog','A plant'],0,I.butterfly,'Living or not?','Living things eat, grow or need water.','A rock does not grow.'),
q(S,'Living things','Ref. I.CN.2.1.1','A plant is living because it can…',['grow','ring','roll','shine'],0,I.plant,'Plant life','A seed can become a plant.','Living things change as they grow.'),
q(S,'Living things','Ref. I.CN.2.1.1','Which living thing makes its own food?',['A plant','A dog','A butterfly','A child'],0,I.tree,'Green plant','Leaves help a plant make food.','Look for the plant.'),
q(S,'Plants','Ref. I.CN.2.1.2','Which part takes in water from the soil?',['Roots','Flower','Fruit','Leaf'],0,I.plant,'Plant parts','Roots grow under the soil.','It is under the ground.'),
q(S,'Plants','Ref. I.CN.2.1.2','Which part holds a plant up?',['Stem','Seed','Fruit','Petal'],0,I.plant,'Stem','The stem supports the plant.','It is the long middle part.'),
q(S,'Plants','Ref. I.CN.2.1.2','Which part is usually green and makes food?',['Leaf','Root','Seed','Fruit'],0,I.tree,'Leaves','Leaves use sunlight.','It grows on a branch or stem.'),
q(S,'Plants','Ref. I.CN.2.1.2','What comes first in a plant life cycle?',['Seed','Flower','Fruit','Tall tree'],0,I.plant,'Plant life cycle','First, we plant a seed.','It is small and goes in the soil.'),
q(S,'Plants','Ref. I.CN.2.1.2','What can a flower become?',['Fruit','Stone','Cloud','Chair'],0,I.plant,'Flower and fruit','Many fruits begin as flowers.','Think about an apple tree.'),
q(S,'Plants','Ref. I.CN.2.1.2','Which action helps a plant?',['Put it near sunlight','Keep it in a dark box','Pull out its roots','Never give it water'],0,I.sun,'Caring for plants','Plants need light and water.','Choose the kind action.'),
q(S,'Animals','Ref. I.CN.2.2.1','Which animal has wings?',['Butterfly','Dog','Fish','Worm'],0,I.butterfly,'Animal body parts','Wings help some animals fly.','Look for an insect that flies.'),
q(S,'Animals','Ref. I.CN.2.2.1','Which animal has fur?',['Dog','Fish','Butterfly','Snail'],0,I.dog,'A dog','A dog has fur and four legs.','Choose the pet with hair.'),
q(S,'Animals','Ref. I.CN.2.2.1','Which animal lives in water?',['Fish','Cat','Chicken','Horse'],0,I.ocean,'Water habitat','Fish use fins to swim.','It has fins.'),
q(S,'Animals','Ref. I.CN.2.2.1','A baby butterfly is first a…',['caterpillar','puppy','chick','kitten'],0,I.butterfly,'Butterfly life cycle','A caterpillar changes into a butterfly.','It crawls before it flies.'),
q(S,'Animals','Ref. I.CN.2.2.1','Which animal lays eggs?',['Chicken','Dog','Cat','Cow'],0,I.dog,'Animal babies','Some animals hatch from eggs.','Think of a farm bird.'),
q(S,'Animals','Ref. I.CN.2.2.1','What helps a fish move?',['Fins','Wings','Hands','Fur'],0,I.ocean,'Fish body','Fins help fish swim.','It moves in water.'),
q(S,'Habitats','Ref. I.CN.2.3.2','Where does a camel live?',['Desert','Ocean','River','Ice'],0,I.desert,'Desert habitat','A desert is hot and dry.','Camels live where there is little rain.'),
q(S,'Habitats','Ref. I.CN.2.3.2','Where does a fish live?',['Water','Tree','Nest','Desert'],0,I.ocean,'Ocean habitat','Fish need water.','Think about swimming.'),
q(S,'Habitats','Ref. I.CN.2.3.2','Where do many birds make a home?',['Nest','River','Cave under water','School bag'],0,I.tree,'Tree habitat','Many nests are in trees.','Birds build it with small sticks.'),
q(S,'Habitats','Ref. I.CN.2.3.2','Which action protects a habitat?',['Put trash in a bin','Throw plastic in a river','Cut every tree','Scare animals'],0,I.recycle,'Protect nature','Clean places keep animals safe.','Choose the clean action.'),
q(S,'Habitats','Ref. I.CN.2.3.2','A frog can live near a…',['pond','dry desk','hot oven','toy box'],0,I.water,'Wet habitat','Frogs need wet places.','Look for water.'),
q(S,'Habitats','Ref. I.CN.2.3.2','A habitat gives an animal…',['food and shelter','a television','a school uniform','a phone'],0,I.tree,'Animal home','A habitat is an animal home.','Animals need food and a safe place.'),
q(S,'My body','Ref. I.CN.2.4.1','Which body part helps you see?',['Eyes','Ears','Nose','Hands'],0,I.eye,'The five senses','We see colors and shapes with our eyes.','You use them to look.'),
q(S,'My body','Ref. I.CN.2.4.1','Which body part helps you hear music?',['Ears','Eyes','Teeth','Feet'],0,I.ear,'Hearing','Our ears hear sounds.','They are on the sides of your head.'),
q(S,'My body','Ref. I.CN.2.4.1','Which sense tells you that a flower smells good?',['Smell','Sight','Hearing','Touch'],0,I.plant,'Sense of smell','Your nose detects smells.','Use your nose.'),
q(S,'My body','Ref. I.CN.2.4.1','What do teeth help us do?',['Chew food','Hear sounds','See colors','Walk'],0,I.tooth,'Healthy teeth','Teeth cut and chew food.','We use them when we eat.'),
q(S,'My body','Ref. I.CN.2.4.1','Which body part helps you walk?',['Legs','Ears','Hair','Teeth'],0,I.walk,'Moving our body','Legs and feet help us move.','Think about running.'),
q(S,'My body','Ref. I.CN.2.4.1','Which sense helps you know ice is cold?',['Touch','Hearing','Smell','Taste'],0,I.water,'Sense of touch','Skin feels hot and cold.','Your skin can feel it.'),
q(S,'Healthy habits','Ref. I.CN.2.6.1','What should you do before eating?',['Wash your hands','Touch the floor','Skip lunch','Play in mud'],0,I.soap,'Clean hands','Soap and water remove germs.','Choose the clean habit.'),
q(S,'Healthy habits','Ref. I.CN.2.6.1','Which food is a healthy snack?',['Apple','Candy','Chips','Lollipop'],0,I.apple,'Healthy food','Fruit helps the body grow.','Choose the fruit.'),
q(S,'Healthy habits','Ref. I.CN.2.6.1','How often should you brush your teeth?',['Every day','Once a year','Never','Only on birthdays'],0,I.tooth,'Clean teeth','Brush in the morning and at night.','It is a daily habit.'),
q(S,'Healthy habits','Ref. I.CN.2.6.1','What helps your body rest?',['Sleep','Loud noise all night','Too much candy','No water'],0,I.moon,'Time to sleep','Children need sleep every night.','We do it at night.'),
q(S,'Healthy habits','Ref. I.CN.2.6.1','What should you drink after exercise?',['Water','Paint','Soap','Glue'],0,I.water,'Drink water','Water keeps the body hydrated.','Choose the safe drink.'),
q(S,'Healthy habits','Ref. I.CN.2.6.1','What should you cover when you cough?',['Mouth','Eyes','Shoes','Book'],0,I.soap,'Stop germs','Use your elbow to cover your mouth.','This helps stop germs.'),
q(S,'Matter','Ref. I.CN.2.7.1','Which one is a liquid?',['Water','Rock','Pencil','Book'],0,I.water,'Liquid water','A liquid flows and takes the shape of a cup.','It can be poured.'),
q(S,'Matter','Ref. I.CN.2.7.1','Which one is a solid?',['Rock','Juice','Air','Rain'],0,I.mountain,'Solid object','A solid keeps its shape.','You can hold it and it stays the same shape.'),
q(S,'Matter','Ref. I.CN.2.7.1','What happens when ice gets warm?',['It melts','It grows','It becomes wood','It sings'],0,I.water,'Ice and water','Warm ice changes into liquid water.','Heat changes ice.'),
q(S,'Matter','Ref. I.CN.2.7.1','Air is a…',['gas','solid','plant','food'],0,I.cloud,'Air around us','Air is a gas that fills spaces.','We breathe it.'),
q(S,'Matter','Ref. I.CN.2.7.1','Which material is best for a raincoat?',['Plastic','Paper','Bread','Cotton candy'],0,I.cloud,'Rainy day','Plastic does not soak up water easily.','Choose a waterproof material.'),
q(S,'Matter','Ref. I.CN.2.7.1','Which object is made of wood?',['Table','Glass of water','Cloud','Juice'],0,I.tree,'Materials','Wood comes from trees.','Think of classroom furniture.'),
q(S,'Weather','Ref. I.CN.2.9.2','What shines in the sky on a sunny day?',['Sun','Book','Fish','Bus'],0,I.sun,'Sunny weather','The Sun gives light and heat.','Look up during the day.'),
q(S,'Weather','Ref. I.CN.2.9.2','What can fall from dark clouds?',['Rain','Pencils','Shoes','Leaves from a book'],0,I.cloud,'Rainy weather','Clouds can bring rain.','Take an umbrella.'),
q(S,'Weather','Ref. I.CN.2.9.2','What should you wear on a cold day?',['Jacket','Swimsuit','Sandals only','Party hat'],0,I.cloud,'Cold weather','Warm clothes protect your body.','Choose warm clothing.'),
q(S,'Weather','Ref. I.CN.2.9.2','Which tool measures temperature?',['Thermometer','Ruler','Clock','Map'],0,I.sun,'Temperature','A thermometer tells hot or cold.','It measures how hot or cold.'),
q(S,'Weather','Ref. I.CN.2.9.2','Wind is moving…',['air','rock','soil','water in a cup'],0,I.cloud,'Windy weather','We can feel moving air.','It can move leaves.'),
q(S,'Weather','Ref. I.CN.2.9.2','Which symbol shows a sunny day?',['Sun','Moon','Umbrella','Snowman'],0,I.sun,'Weather symbol','A bright Sun means sunny weather.','Choose the yellow star in the sky.'),
q(S,'Day and night','Ref. I.CN.2.10.1','What do we usually see in the sky at night?',['Moon','School bus','Rainbow every night','Sun high in the sky'],0,I.moon,'Night sky','The Moon is easy to see at night.','It is not the Sun.'),
q(S,'Day and night','Ref. I.CN.2.10.1','When do we usually go to school?',['Day','Midnight','Very late at night','While sleeping'],0,I.sun,'Daytime','The Sun is up when school begins.','Think about the morning.'),
q(S,'Day and night','Ref. I.CN.2.10.1','The Sun gives us…',['light and heat','rain and snow','books and pencils','food and shoes'],0,I.sun,'Our Sun','Sunlight makes daytime bright.','It is bright and warm.'),
q(S,'Day and night','Ref. I.CN.2.10.1','What do many people do at night?',['Sleep','Go to school','Eat breakfast','See the noon Sun'],0,I.moon,'Night routine','Night is time to rest.','We go to bed.'),
q(S,'Day and night','Ref. I.CN.2.10.1','Earth turns to make…',['day and night','new trees','more oceans','toys'],0,I.earth,'Planet Earth','One side faces the Sun, then the other.','Think about light and darkness.'),
q(S,'Day and night','Ref. I.CN.2.10.1','Which object is a star?',['Sun','Moon','Earth','Cloud'],0,I.sun,'A star near Earth','The Sun is our closest star.','It gives Earth light.'),
q(S,'Earth care','Ref. I.CN.2.11.1','Where should a plastic bottle go?',['Recycling bin','River','Street','Forest floor'],0,I.recycle,'Recycle','Put waste in the correct bin.','Choose the clean place.'),
q(S,'Earth care','Ref. I.CN.2.11.1','How can you save water?',['Turn off the tap','Leave the tap open','Play with a hose all day','Throw water away'],0,I.water,'Save water','Use only the water you need.','Close the tap.'),
q(S,'Earth care','Ref. I.CN.2.11.1','Which action helps trees?',['Use both sides of paper','Waste paper','Break branches','Cut young trees'],0,I.tree,'Care for trees','Using less paper saves resources.','Do not waste paper.'),
q(S,'Earth care','Ref. I.CN.2.11.1','What can we reuse?',['A clean bottle','Smoke','Dirty river water','Thunder'],0,I.recycle,'Reuse objects','Use an object again instead of throwing it away.','Choose an object.'),
q(S,'Earth care','Ref. I.CN.2.11.1','What keeps a park clean?',['Pick up trash','Drop wrappers','Write on trees','Leave bottles'],0,I.tree,'Clean park','Trash belongs in a bin.','Choose the responsible action.'),
q(S,'Earth care','Ref. I.CN.2.11.1','Why should we care for animals?',['They are living things','They are toys','They never need food','They cannot feel'],0,I.dog,'Care for animals','Animals need food, water and safety.','Animals are alive.')
];
const social=[
q(SS,'Family','Ref. I.CS.2.1.1','Which action helps your family?',['Put away your toys','Make a big mess','Break things','Shout at everyone'],0,I.family,'Family responsibility','At home, everyone can help.','Choose the helpful action.'),
q(SS,'Family','Ref. I.CS.2.1.1','A family gives children…',['care and love','traffic lights','homework only','bus tickets'],0,I.family,'Families care','Families protect and support children.','Think about people who care for you.'),
q(SS,'Family','Ref. I.CS.2.1.1','What should family members do?',['Respect each other','Hit each other','Hide every problem','Break rules'],0,I.family,'Family respect','We listen and speak kindly.','Choose the kind action.'),
q(SS,'Family','Ref. I.CS.2.1.1','Which is a responsibility at home?',['Make your bed','Leave trash on the floor','Take things without asking','Draw on walls'],0,I.home,'Helping at home','Small jobs help the family.','Choose a useful job.'),
q(SS,'Family','Ref. I.CS.2.1.1','Families can be…',['different and special','all exactly the same','only very large','only very small'],0,I.family,'Every family is unique','Families have many forms.','People live in different kinds of families.'),
q(SS,'Family','Ref. I.CS.2.1.1','What is a good way to solve a family problem?',['Talk calmly','Scream','Push','Run away without telling'],0,I.family,'Talk and listen','Kind words help solve problems.','Use words and listen.'),
q(SS,'School','Ref. I.CS.2.3.1','Why do children go to school?',['To learn','To sleep all day','To drive buses','To sell food'],0,I.school,'Our school','At school we learn with teachers and friends.','Think about classes.'),
q(SS,'School','Ref. I.CS.2.3.1','Who helps students learn?',['Teacher','Pilot','Chef','Farmer'],0,I.books,'People at school','A teacher guides the class.','This person works in a classroom.'),
q(SS,'School','Ref. I.CS.2.3.1','What should you do before speaking in class?',['Raise your hand','Shout','Stand on the desk','Leave the room'],0,I.school,'Class rule','Wait for your turn to speak.','Use your hand.'),
q(SS,'School','Ref. I.CS.2.3.1','Where can you find many books?',['Library','Kitchen','Parking lot','Bathroom'],0,I.books,'School library','A library is a place to read.','Look for books.'),
q(SS,'School','Ref. I.CS.2.3.1','How should we treat classmates?',['With respect','With pushes','With insults','By taking their things'],0,I.school,'Good classmates','Kind actions make school safe.','Choose kindness.'),
q(SS,'School','Ref. I.CS.2.3.1','What keeps the classroom organized?',['Follow the rules','Throw materials','Run between desks','Leave everything out'],0,I.school,'Classroom rules','Rules help everyone learn safely.','Choose the safe action.'),
q(SS,'Community helpers','Ref. I.CS.2.4.1','Who puts out fires?',['Firefighter','Baker','Singer','Painter'],0,I.fire,'Firefighter','Firefighters use special trucks and water.','This person fights fires.'),
q(SS,'Community helpers','Ref. I.CS.2.4.1','Who helps sick people?',['Doctor','Driver','Carpenter','Farmer'],0,I.hospital,'Health worker','Doctors and nurses work in health centers.','This person works at a hospital.'),
q(SS,'Community helpers','Ref. I.CS.2.4.1','Who helps keep people safe?',['Police officer','Musician','Cook','Dancer'],0,I.police,'Police officer','Police officers protect the community.','Look for the safety worker.'),
q(SS,'Community helpers','Ref. I.CS.2.4.1','Who grows food on a farm?',['Farmer','Pilot','Dentist','Librarian'],0,I.apple,'Farmer','Farmers grow plants and care for animals.','This person works with crops.'),
q(SS,'Community helpers','Ref. I.CS.2.4.1','Who drives a public bus?',['Bus driver','Doctor','Teacher','Firefighter'],0,I.bus,'Bus driver','A driver takes people from place to place.','This person controls the bus.'),
q(SS,'Community helpers','Ref. I.CS.2.4.1','Who takes care of books in a library?',['Librarian','Chef','Police officer','Mechanic'],0,I.books,'Librarian','A librarian organizes books and helps readers.','This person works with books.'),
q(SS,'Community places','Ref. I.CS.2.4.1','Where do sick people go for help?',['Hospital','Park','Bakery','Bus stop'],0,I.hospital,'Hospital','Doctors and nurses help people here.','It is a health place.'),
q(SS,'Community places','Ref. I.CS.2.4.1','Where can children play outside?',['Park','Hospital room','Police station','Factory'],0,I.tree,'Community park','Parks have open spaces and plants.','Choose the outdoor place.'),
q(SS,'Community places','Ref. I.CS.2.4.1','Where do we borrow books?',['Library','Fire station','Market','Airport'],0,I.books,'Library','Books can be read and borrowed here.','Look for the place with books.'),
q(SS,'Community places','Ref. I.CS.2.4.1','Where can we buy food?',['Market','School library','Fire station','Playground'],0,I.apple,'Market','People buy and sell food at a market.','Choose the shopping place.'),
q(SS,'Community places','Ref. I.CS.2.4.1','Where do firefighters work?',['Fire station','Library','Farm','Museum'],0,I.fire,'Fire station','Fire trucks leave from this place.','It is the firefighters’ building.'),
q(SS,'Community places','Ref. I.CS.2.4.1','Which place is part of a community?',['School','Moon','Cloud','Ocean floor'],0,I.school,'Our community','People learn and work in community places.','Choose a place people use every day.'),
q(SS,'Rules and safety','Ref. I.CS.2.3.2','What should you do at a red traffic light?',['Stop','Run','Dance in the road','Cross quickly'],0,I.traffic,'Traffic light','Red means stop.','Remember the red color.'),
q(SS,'Rules and safety','Ref. I.CS.2.3.2','Where is the safest place to cross a street?',['Crosswalk','Middle of the road','Behind a bus','Between parked cars'],0,I.walk,'Safe crossing','Use the marked lines and look both ways.','Look for white lines.'),
q(SS,'Rules and safety','Ref. I.CS.2.3.2','What should you wear in a car?',['Seat belt','Backpack','Blanket over your head','Roller skates'],0,I.bus,'Travel safely','A seat belt protects your body.','It clicks across your body.'),
q(SS,'Rules and safety','Ref. I.CS.2.3.2','Why do communities have rules?',['To keep people safe','To make people sad','To stop all games','To make streets dirty'],0,I.police,'Rules protect us','Good rules help people live together.','Think about safety.'),
q(SS,'Rules and safety','Ref. I.CS.2.3.2','Before crossing a street, you should…',['look both ways','close your eyes','run without looking','play in the road'],0,I.walk,'Look left and right','Check that cars have stopped.','Use your eyes.'),
q(SS,'Rules and safety','Ref. I.CS.2.3.2','Who should a child ask for help when lost?',['A trusted adult','Another lost child','Nobody','A toy'],0,I.police,'Ask for help','Find a police officer, teacher or trusted adult.','Choose a safe adult.'),
q(SS,'Maps','Ref. I.CS.2.2.1','What helps us find places?',['Map','Spoon','Pillow','Song'],0,I.map,'A simple map','Maps show places with symbols.','It shows roads and places.'),
q(SS,'Maps','Ref. I.CS.2.2.1','What does a map symbol show?',['A place or object','A taste','A sound only','A bedtime'],0,I.map,'Map symbols','Small pictures stand for real places.','Symbols give information.'),
q(SS,'Maps','Ref. I.CS.2.2.1','If the school is beside the park, it is…',['next to the park','under the park','inside the river','above the clouds'],0,I.school,'Position words','Beside means next to.','The two places are close.'),
q(SS,'Maps','Ref. I.CS.2.2.1','Which word tells location?',['near','sing','eat','happy'],0,I.map,'Location words','Near tells where something is.','Choose the place word.'),
q(SS,'Maps','Ref. I.CS.2.2.1','A route tells us…',['how to get to a place','what food tastes like','how loud music is','when to sleep'],0,I.map,'Follow a route','A route is a path from one place to another.','It gives directions.'),
q(SS,'Maps','Ref. I.CS.2.2.1','Which place can be a reference point?',['School','A tiny ant','A moving cloud','A song'],0,I.school,'Reference point','A known building helps us know where we are.','Choose a place that stays still.'),
q(SS,'Transport','Ref. I.CS.2.4.2','Which transport moves on a road?',['Bus','Boat','Airplane','Canoe'],0,I.bus,'Land transport','A bus has wheels and uses streets.','Choose the vehicle with wheels.'),
q(SS,'Transport','Ref. I.CS.2.4.2','Which transport moves on water?',['Boat','Bus','Bicycle','Train'],0,I.ocean,'Water transport','A boat floats.','Choose the vehicle for a river or ocean.'),
q(SS,'Transport','Ref. I.CS.2.4.2','Which transport flies?',['Airplane','Bus','Boat','Bicycle'],0,I.cloud,'Air transport','An airplane has wings.','Look in the sky.'),
q(SS,'Transport','Ref. I.CS.2.4.2','What is public transport?',['A bus many people can use','One child’s toy car','A private bedroom','A classroom chair'],0,I.bus,'Public bus','Many passengers share public transport.','Many people ride it.'),
q(SS,'Transport','Ref. I.CS.2.4.2','Which transport is good for a short trip and exercise?',['Bicycle','Airplane','Ship','Helicopter'],0,I.walk,'Move with your body','Pedaling a bicycle uses your legs.','It has two wheels.'),
q(SS,'Transport','Ref. I.CS.2.4.2','Where do people wait for a bus?',['Bus stop','Swimming pool','Kitchen','Bedroom'],0,I.bus,'Bus stop','A bus stops here for passengers.','It is beside the road.'),
q(SS,'Ecuador','Ref. I.CS.2.6.1','What is the name of our country?',['Ecuador','Canada','Japan','Egypt'],0,I.ecuador,'Our country','We live in Ecuador.','Look at our flag.'),
q(SS,'Ecuador','Ref. I.CS.2.6.1','Ecuador is in…',['South America','Europe','Asia','Africa'],0,I.earth,'Ecuador on Earth','Ecuador is a South American country.','It is part of the Americas.'),
q(SS,'Ecuador','Ref. I.CS.2.6.1','Which colors are on Ecuador’s flag?',['Yellow, blue and red','Pink, black and white','Green and purple','Orange and gray'],0,I.ecuador,'Ecuadorian flag','Our flag has three main colors.','Look carefully at the flag.'),
q(SS,'Ecuador','Ref. I.CS.2.6.1','What city is the capital of Ecuador?',['Quito','Cuenca','Loja','Manta'],0,I.mountain,'Quito','Quito is Ecuador’s capital city.','We live near this capital city.'),
q(SS,'Ecuador','Ref. I.CS.2.6.1','People born in Ecuador are…',['Ecuadorian','European','Asian','Australian'],0,I.ecuador,'Ecuadorian identity','Our nationality connects us to Ecuador.','Use the country name.'),
q(SS,'Ecuador','Ref. I.CS.2.6.1','Which is a national symbol?',['Flag','School desk','Toy car','Spoon'],0,I.ecuador,'National symbols','The flag represents Ecuador.','It has yellow, blue and red.'),
q(SS,'Ecuador regions','Ref. I.CS.2.6.2','Which region has many high mountains?',['Sierra','Costa','Insular','Ocean'],0,I.mountain,'The Sierra','The Andes mountains cross the Sierra.','Think of Quito and the Andes.'),
q(SS,'Ecuador regions','Ref. I.CS.2.6.2','Which region is beside the Pacific Ocean?',['Costa','Sierra','Amazonía','Mountain top'],0,I.ocean,'The Coast','The Costa has beaches and warm lowlands.','Costa means coast.'),
q(SS,'Ecuador regions','Ref. I.CS.2.6.2','Which region has a large rainforest?',['Amazonía','Costa','Sierra','Desert'],0,I.tree,'The Amazon','The Amazon has many rivers, plants and animals.','Think of the rainforest.'),
q(SS,'Ecuador regions','Ref. I.CS.2.6.2','The Galápagos Islands are in the…',['Insular Region','Sierra','Amazonía','city of Quito'],0,I.ocean,'The Insular Region','Galápagos is a group of islands.','Insular means islands.'),
q(SS,'Ecuador regions','Ref. I.CS.2.6.2','How many natural regions does Ecuador have?',['Four','One','Two','Ten'],0,I.ecuador,'Four regions','Costa, Sierra, Amazonía and Insular.','Count the four named regions.'),
q(SS,'Ecuador regions','Ref. I.CS.2.6.2','In which region is Quito?',['Sierra','Costa','Amazonía','Insular'],0,I.mountain,'Quito in the Andes','Quito is high in the mountains.','Choose the mountain region.'),
q(SS,'Rights','Ref. I.CS.2.3.2','Which is a child’s right?',['Education','Dangerous work','No food','No care'],0,I.school,'Right to education','Every child has the right to learn.','Children go to school to learn.'),
q(SS,'Rights','Ref. I.CS.2.3.2','Which is a child’s right?',['A name','To hurt others','To break rules','To take anything'],0,I.family,'Right to identity','Every child has a name and identity.','It is what people call you.'),
q(SS,'Rights','Ref. I.CS.2.3.2','Children have the right to…',['health care','drive a car','miss every class','hurt animals'],0,I.hospital,'Right to health','Children should receive care when sick.','Doctors help protect this right.'),
q(SS,'Rights','Ref. I.CS.2.3.2','A right comes with…',['responsibility','permission to hurt','no rules','only prizes'],0,I.school,'Rights and duties','We respect other people’s rights too.','We also have duties.'),
q(SS,'Rights','Ref. I.CS.2.3.2','Which action respects another child?',['Listen when they speak','Laugh at them','Take their pencil','Push them'],0,I.family,'Respect','Every child deserves kind treatment.','Choose the kind action.'),
q(SS,'Rights','Ref. I.CS.2.3.2','Who has rights?',['All children','Only adults','Only teachers','Only athletes'],0,I.family,'Rights for everyone','Every child has the same basic rights.','No child is left out.')
];
const $=id=>document.getElementById(id),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const pickFive=bank=>{const groups={};bank.forEach(x=>(groups[x.topic]??=[]).push(x));return shuffle(Object.values(groups)).slice(0,5).map(g=>shuffle(g)[0])};
let items=[],index=0,score=0,eggs=0,student='',log=[],usedHelp={fifty:false,rex:false},currentChoices=[],rubricIndex=null,musicOn=true,audioCtx=null,musicTimer=null,musicStep=0;
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function start(){student=$('studentName').value.trim();if(!student){$('nameError').textContent='Please write the student’s name.';return}$('nameError').textContent='';items=shuffle([...pickFive(science),...pickFive(social)]);index=score=eggs=0;log=[];usedHelp={fifty:false,rex:false};$('studentLabel').textContent=student;show('gameScreen');startMusic();render()}
function render(){const item=items[index];$('questionNumber').textContent=index+1;$('progressBar').style.width=`${((index+1)/10)*100}%`;$('subjectPill').textContent=item.area;$('subjectPill').dataset.area=item.area;$('topicLabel').textContent=`${item.area==='Science'?'🔬':'🌎'} ${item.topic}`;$('streakLabel').textContent=`🥚 Eggs: ${eggs}`;$('questionImage').src=item.image;$('questionImage').alt=`Reference picture for ${item.area}`;$('questionText').textContent=item.prompt;$('clue').className='clue';$('clue').textContent='';$('feedback').className='feedback';$('feedback').textContent='';$('nextBtn').classList.remove('show');$('answers').innerHTML='';$('fiftyBtn').disabled=usedHelp.fifty;$('rexHelpBtn').disabled=usedHelp.rex;renderChoices(item)}
function renderChoices(item){const correctText=item.choices[item.correct];currentChoices=shuffle(item.choices).map(text=>({text,correct:text===correctText}));currentChoices.forEach((c,i)=>{const b=document.createElement('button');b.className='answer';b.dataset.correct=c.correct;b.innerHTML=`<span>${'ABCD'[i]}</span>${escapeHtml(c.text)}`;b.onclick=()=>answer(b,c,item);$('answers').appendChild(b)})}
function answer(button,choice,item){document.querySelectorAll('.answer').forEach(b=>{b.disabled=true;if(b.dataset.correct==='true')b.classList.add('correct')});if(choice.correct){score++;eggs++;button.classList.add('bounce');$('feedback').textContent='🥚 ROAR-SOME! Correct!';$('feedback').className='feedback good';tone(659,.1);eggPop()}else{button.classList.add('wrong');$('feedback').textContent=`Good try! ${item.hint}`;$('feedback').className='feedback bad';tone(196,.16)}log.push({area:item.area,topic:item.topic,indicator:item.indicator,prompt:item.prompt,correct:choice.correct,earned:choice.correct?1:0,max:1,response:choice.text,answer:item.choices[item.correct]});$('streakLabel').textContent=`🥚 Eggs: ${eggs}`;showNext()}
function showNext(){$('nextBtn').textContent=index===9?'FINISH ADVENTURE ▶':'NEXT MISSION ▶';$('nextBtn').classList.add('show')}
function next(){index++;if(index<10)render();else finish()}
function finish(){stopMusic();const result={id:Date.now(),student,date:new Date().toLocaleString(),science:areaScore(S),social:areaScore(SS),log};result.total=result.science+result.social;const data=getResults();data.push(result);saveResults(data);rubricIndex=data.length-1;$('scoreValue').textContent=`${result.total.toFixed(2)}/10`;$('resultMessage').textContent='Your two automatic rubrics are ready.';$('breakdown').innerHTML=`<span>🔬 Science: <b>${result.science.toFixed(2)}/5</b></span><span>🌎 Social Studies: <b>${result.social.toFixed(2)}/5</b></span>`;$('resultRubrics').innerHTML=rubricSummary(result,S,result.science,'🔬')+rubricSummary(result,SS,result.social,'🌎');show('resultScreen')}
function areaScore(area){return log.filter(x=>x.area===area).reduce((n,x)=>n+x.earned,0)}
function speakCurrent(){const item=items[index];if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(item.prompt+' '+item.choices.join('. '));u.lang='en-US';u.rate=.68;window.speechSynthesis.speak(u)}
function fifty(){shuffle([...document.querySelectorAll('.answer')].filter(b=>b.dataset.correct==='false')).slice(0,2).forEach(b=>b.classList.add('hidden'));usedHelp.fifty=true;$('fiftyBtn').disabled=true}
function rexHelp(){const item=items[index];usedHelp.rex=true;$('rexHelpBtn').disabled=true;$('clue').textContent=`🦖 Rex says: ${item.hint}`;$('clue').classList.add('show')}
function eggPop(){const e=document.createElement('div');e.className='egg-pop';e.textContent='🥚';document.body.appendChild(e);setTimeout(()=>e.remove(),850)}
function newStudent(){$('studentName').value='';show('startScreen');$('studentName').focus()}
function getResults(){return JSON.parse(localStorage.getItem('rexDiagnosticV3')||'[]')}
function saveResults(data){localStorage.setItem('rexDiagnosticV3',JSON.stringify(data))}
function performance(n){if(n===5)return['Excellent','Shows secure understanding.'];if(n===4)return['Achieved','Shows expected understanding.'];if(n===3)return['Developing','Understands some ideas; needs brief reinforcement.'];if(n>0)return['Beginning','Needs guided practice and visual support.'];return['Needs support','Needs direct support with the assessed ideas.']}
function renderResults(){const data=getResults();$('resultsBody').innerHTML=data.length?data.map((r,i)=>`<tr><td>${escapeHtml(r.student)}</td><td>${r.science.toFixed(2)}</td><td>${r.social.toFixed(2)}</td><td class="final">${(r.science+r.social).toFixed(2)}/10</td><td><button class="rubric-btn" onclick="openRubric(${i})">View both</button></td></tr>`).join(''):'<tr><td colspan="5">No students have completed the assessment yet.</td></tr>';$('dashboardRubrics').innerHTML=data.map((r,i)=>`<details><summary><span>${escapeHtml(r.student)}</span><b>${(r.science+r.social).toFixed(2)} / 10</b></summary><div class="dashboard-rubric-summary">${rubricSummary(r,S,r.science,'🔬')}${rubricSummary(r,SS,r.social,'🌎')}<button class="rubric-btn" onclick="openRubric(${i})">OPEN COMPLETE RUBRICS</button></div></details>`).join('')}
function openDashboard(){renderResults();$('teacherDialog').showModal()}
function rubricTable(r,area,subjectScore,emoji){const rows=r.log.filter(x=>x.area===area);const [level,description]=performance(subjectScore);return `<section class="rubric-section subject-rubric"><div class="rubric-title"><div><span class="eyebrow">${emoji} ${area.toUpperCase()}</span><h3>Diagnostic rubric · ${subjectScore.toFixed(2)} / 5</h3></div><span class="level-badge">${level}</span></div><p class="indicator"><b>How it is scored:</b> 5 questions × 1 point. A correct answer earns 1 point; an incorrect answer earns 0. Total: 5 points.</p><table class="auto-rubric"><thead><tr><th>Criterion / topic</th><th>Evaluation indicator</th><th>Evidence</th><th>Score</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${escapeHtml(x.topic)}</b><br><small>${escapeHtml(x.prompt)}</small></td><td>${escapeHtml(x.indicator)}</td><td class="${x.correct?'met':'support'}">${x.correct?'Achieved':'Needs support'}<br><small>Answer: ${escapeHtml(x.response)}</small></td><td><b>${x.earned} / 1</b></td></tr>`).join('')}</tbody><tfoot><tr><td colspan="3"><b>Performance:</b> ${level} — ${description}</td><td><b>${subjectScore.toFixed(2)} / 5</b></td></tr></tfoot></table></section>`}
function rubricSummary(r,area,subjectScore,emoji){const [level]=performance(subjectScore),correct=r.log.filter(x=>x.area===area&&x.correct).length;return `<article class="result-rubric-card"><span>${emoji}</span><div><small>AUTOMATIC RUBRIC</small><h3>${area}</h3><p>${correct} of 5 indicators achieved · <b>${level}</b></p></div><strong>${subjectScore.toFixed(2)} / 5</strong></article>`}
function openRubric(i){rubricIndex=i;const r=getResults()[i];$('rubricStudent').textContent=r.student;$('rubricContent').innerHTML=rubricTable(r,S,r.science,'🔬')+rubricTable(r,SS,r.social,'🌎');$('rubricTotal').textContent=`${(r.science+r.social).toFixed(2)} / 10`;$('rubricDialog').showModal()}
function download(){const data=getResults();if(!data.length)return;const head=['Student','Date','Science /5','Science level','Social Studies /5','Social Studies level','Final /10','Question details'];const rows=[head,...data.map(r=>[r.student,r.date,r.science.toFixed(2),performance(r.science)[0],r.social.toFixed(2),performance(r.social)[0],(r.science+r.social).toFixed(2),r.log.map(x=>`${x.area} | ${x.topic} | ${x.correct?'Achieved':'Needs support'} | ${x.earned}/1`).join(' ; ')])];const csv=rows.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='rex-diagnostic-dashboard.csv';a.click();URL.revokeObjectURL(a.href)}
function clearResults(){if(confirm('Delete all diagnostic results from this device?')){localStorage.removeItem('rexDiagnosticV3');renderResults()}}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function tone(freq,duration=.12,volume=.035){if(!musicOn)return;ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration)}
function startMusic(){if(!musicOn||musicTimer)return;ensureAudio();const melody=[262,330,392,523,392,330,294,392];musicTimer=setInterval(()=>tone(melody[musicStep++%melody.length],.22,.018),420)}
function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function toggleMusic(){musicOn=!musicOn;$('musicBtn').textContent=`🎵 Music: ${musicOn?'ON':'OFF'}`;$('musicBtn').setAttribute('aria-pressed',musicOn);if(musicOn&&$('gameScreen').classList.contains('active'))startMusic();else stopMusic()}
$('startBtn').onclick=start;$('studentName').onkeydown=e=>{if(e.key==='Enter')start()};$('nextBtn').onclick=next;$('newStudentBtn').onclick=newStudent;$('openCurrentRubricsBtn').onclick=()=>openRubric(rubricIndex);$('fiftyBtn').onclick=fifty;$('rexHelpBtn').onclick=rexHelp;$('speakBtn').onclick=speakCurrent;$('teacherBtn').onclick=openDashboard;$('musicBtn').onclick=toggleMusic;$('closeDialog').onclick=()=>$('teacherDialog').close();$('closeRubric').onclick=()=>$('rubricDialog').close();$('printRubricBtn').onclick=()=>window.print();$('downloadBtn').onclick=download;$('clearBtn').onclick=clearResults;
